### ISSUE TITLE
License

### ISSUE THREAD

**Issue by doubleo2** [synapticloop/routemaster#1]
Can you please provide a license for routemaster?

Thanks,
Enrico

**Comment by synapticloop** [comment]
Indeed, I am just bringing the routemaster up to the latest.  the ant task download-dependencies will go and get the license file, however github seems to be blocking (??) direct downloads of from raw.githubusercontent.com.

**Comment by synapticloop** [comment]
license added

**Comment by doubleo2** [comment]
Just for future reference, [the license](https://github.com/synapticloop/routemaster/blob/2c9d68c5a514dd055f319b4471e5dfd3e300489a/src/main/resources/LICENSE.md) is in src/main/resources, not in the top-level directory.

Thanks @synapticloop for routemaster and for adding the license.
