### ISSUE TITLE
Add to maven / jcenter

### ISSUE THREAD

**Issue by eliasbagley** [synapticloop/routemaster#4]
It would be great if if this was on maven or jcenter so I don't have to manually include the jar in my project.

**Comment by synapticloop** [comment]
Thanks for your interest, I am creating a jcenter repository.

**Comment by synapticloop** [comment]
now included in jcenter

should be able to resolve dependencies for
 `<dependency>`
`<groupId>synapticloop</groupId>`
`<artifactId>routemaster-templar</artifactId>`
`<version>v1.1.0</version>`
`<type>jar</type>`
`</dependency>`

or

`<dependency>`
`<groupId>synapticloop</groupId>`
`<artifactId>routemaster</artifactId>`
`<version>v1.1.0</version>`
`<type>jar</type>`
`</dependency>`

You may need to set up your repositories

`<repository>`
`<snapshots>`
`<enabled>false</enabled>`
`</snapshots>`
`<id>bintray-synapticloop-maven</id>`
`<name>bintray</name>`
`<url>http://dl.bintray.com/synapticloop/maven/templar</url>`
`</repository>`

until jcenter sync the repository

leaving this ticket open until confirmation
